<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <OutputType>Exe</OutputType>
      <Nullable>disable</Nullable>
      <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Company>PDF Tools AG</Company>
    <Product>ToolboxAddBarcode</Product>
    <Copyright>Copyright © PDF Tools AG 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfTools.Toolbox" Version="1.13.0" />
  </ItemGroup>
</Project>